void drawRuler(GtkWidget*);
void drawBackground(cairo_t*);
void drawLines(cairo_t*);
void drawNumbers(cairo_t*);
void drawCursorMark(cairo_t*, int);
void drawPositionNotifier(cairo_t *, cairo_t*, int);
void drawCap(cairo_t*);
void drawRotateButton(cairo_t*);
void drawMenuButton(cairo_t*);
void drawTranslucentOverlay(cairo_t*);
void drawOutline(cairo_t*);
void rendertext(cairo_t*, char*, int, int);
gboolean isInRotateButton(int, int);
